% plot_modes(IN,OUT,solnum_list,scale_opt) plots the field profiles of the
% calculated modes. It takes the following parameters
%
%           IN          :       The input structure defined in the main script
%           OUT         :       The output structure generated by the solver
%           solnum_list :       The list of the solutions whose field profiles needs to be plotted 
%           scale_opt   :       'lin'  or 'log' scale of field profiles

function plot_modes(IN,OUT,solnum_list,scale_opt)

um = IN.const.um;

x_i = IN.geom.x_i;
y_i = IN.geom.y_i;

[ny nx] = size(IN.mater.epsr);

nyx = nx * ny;

x_min = x_i(1);
x_max = x_i(nx);
y_min = y_i(1);
y_max = y_i(ny);

ncont = 100;
nsol = length(solnum_list);

switch scale_opt
    
    case 'lin'
    
        for sn = 1 : nsol

            solnum = solnum_list(sn);        

            f2=figure(solnum);

            subplot(2,1,1);    
            contourf(x_i/um,y_i/um,real(OUT(solnum).Ex),...
                     ncont,...
                     'LineStyle','none'); 
            axis equal; 
            axis([x_min x_max y_min y_max]/um);        
            title(strcat('neff = ',...
                          num2str(OUT(solnum).neff)),...
                          'interpreter','latex','Fontsize',15);

            colormap jet; 

            subplot(2,1,2);    
            contourf(x_i/um,y_i/um,real(OUT(solnum).Ey),...
                     ncont,...
                     'LineStyle','none'); 
            axis equal; 
            axis([x_min x_max y_min y_max]/um);           

        end

    
    case'log'

        for sn = 1 : length(solnum_list)

            solnum = solnum_list(sn);

            f2=figure(solnum);

            subplot(2,1,1);    
            contourf(x_i/um,y_i/um,log10(abs(real(OUT(solnum).Ex))),...
                     ncont,...
                     'LineStyle','none'); 
            axis equal; 
            axis([x_min x_max y_min y_max]/um);        
            title(strcat('neff = ',...
                          num2str(OUT(solnum).neff)),...
                          'interpreter','latex','Fontsize',15);

            colormap jet; 

            subplot(2,1,2);    
            contourf(x_i/um,y_i/um,log10(abs(real(OUT(solnum).Ey))),...
                     ncont,...
                     'LineStyle','none'); 
            axis equal; 
            axis([x_min x_max y_min y_max]/um);
            
        end
    
    otherwise
        fprintf(['\n\n UNKNOWN OPTION.''' scale_opt ''' \n\nONLY SCALE OPTIONS ARE ' '''log''' 'and' '''lin''' '\n\n']);
    
end