% plot_modes(IN,OUT,solnum_list,scale_opt) plots the field profiles of the
% calculated modes. It takes the fi=ollowing parameters
%
%           IN          :       The input structure defined in the main script
%           OUT         :       The output structure generated by the solver
%           solnum_list :       The list of the solutions whose field profiles needs to be plotted 
%           scale_opt   :       'lin'  or 'log' scale of field profiles

function plot_modes(IN,OUT,solnum_list,scale_opt)

um = IN.const.um;

r_i = IN.geom.r_i;
z_i = IN.geom.z_i;

[nz nr] = size(IN.mater.epsr);

Nzr = nr * nz;

r_min = r_i(1);
r_max = r_i(nr);
z_min = z_i(1);
z_max = z_i(nz);

ncont = 100;
nsol = length(solnum_list);

switch scale_opt
    
    case 'lin'
    
        for sn = 1 : nsol

            solnum = solnum_list(sn);        

            f2=figure(solnum);

            subplot(2,1,1);    
            contourf(r_i/um,z_i/um,real(OUT(solnum).Er),...
                     ncont,...
                     'LineStyle','none'); 
            axis equal; 
            axis([r_min r_max z_min z_max]/um);        
            title(strcat('$\lambda = ',...
                          num2str(OUT(solnum).lambda0/um),...
                          '\,\mu\mathrm{m}$'),...
                          'interpreter','latex','Fontsize',15);

            colormap jet; 

            subplot(2,1,2);    
            contourf(r_i/um,z_i/um,real(OUT(solnum).Ez),...
                     ncont,...
                     'LineStyle','none'); 
            axis equal; 
            axis([r_min r_max z_min z_max]/um);


        end

    
    case 'log'

        for sn = 1 : length(solnum_list)

            solnum = solnum_list(sn);

            f2=figure(solnum);

            subplot(2,1,1);    
            contourf(r_i/um,z_i/um,log10(abs(real(OUT(solnum).Er))),...
                     ncont,...
                     'LineStyle','none'); 
            axis equal; 
            axis([r_min r_max z_min z_max]/um);        
            title(strcat('$\lambda = ',...
                          num2str(OUT(solnum).lambda0/um),...
                          '\,\mu\mathrm{m}$'),...
                          'interpreter','latex','Fontsize',15);

            colormap jet; 

            subplot(2,1,2);    
            contourf(r_i/um,z_i/um,log10(abs(real(OUT(solnum).Ez))),...
                     ncont,...
                     'LineStyle','none'); 
            axis equal; 
            axis([r_min r_max z_min z_max]/um);


        end
    
    otherwise
        fprintf(['\n\n UNKNOWN OPTION.''' scale_opt ''' \n\nONLY SCALE OPTIONS ARE ' '''log''' 'and' '''lin''' '\n\n']);
    
end